api/urls.py
from django.urls import  include, path
from django.views.decorators.csrf import csrf_exempt

from .views import *
#
from rest_framework.routers import DefaultRouter
from .viewsets import CategoryViewSet, SizesViewSet, GroupedSizesViewSet

router = DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'sizes', SizesViewSet)
#router.register(r'grouped-sizes', GroupedSizesViewSet)

urlpatterns = [

    path('', include(router.urls)),
    path('grouped-sizes/filter_by_category/', GroupedSizesViewSet.as_view({'get': 'filter_by_category'})),
    path('create/', CombinedCreateView.as_view(), name='combined-create'),
]

inventory/urls.py
from django.conf.urls.static import static
from django.urls import path, include

from . import settings
from .views import dashboard
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import ChangePasswordView

urlpatterns = [
    path('management/', admin.site.urls, name='management'),
    path('', dashboard, name='dashboard'),
    path('store/', include('store.urls')),
    path('api/', include('api.urls')),
    path('pos/', include('pos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),

]

# urls.py
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Mender POS'
admin.site.site_title = 'Mender POS'

store/urls.py
from django.urls import  include, path
from django.views.decorators.csrf import csrf_exempt

from .views import *
#
from rest_framework.routers import DefaultRouter


#router.register(r'grouped-sizes', GroupedSizesViewSet)

urlpatterns = [
    path('products/by-sku/<str:sku>/', GetProductBySkuView.as_view(), name='get_product_by_sku'),
    path('product-list', ProductListView.as_view(), name='product-list'),
    path('generate-barcode/<str:sku>/',GenerateBarcode.as_view(), name='generate-barcode'),
    path('add-product/',addProduct,name='add-product'),
]

store/models.py
from django.core.validators import RegexValidator
from django.db import models


# import barcode
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

from .Barcode import BarcodeEAN13


class Category(models.Model):
    name = models.CharField(max_length=120)
    comment = models.CharField(max_length=220, blank=True, null=True)

    def __str__(self):
        return self.name


class Sizes(models.Model):
    size = models.CharField(max_length=15)
    def __str__(self):
        return self.size


class GroupedSizes(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    size = models.ForeignKey(Sizes, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.category) + str(self.size)


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50,unique=True)
    color = models.CharField(max_length=120, null=True, blank=True)
    description = models.CharField(max_length=120, null=True, blank=True)
    image = models.ImageField(upload_to='media/', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class ProductDetail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    sku = models.CharField(max_length=30,unique=True,validators=[
        RegexValidator('^([0-9]{13})|([0]{1})$'
        ),
    ])
    size = models.CharField(max_length=30, blank=True, null=True)
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)
    cost_price = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)


    def __str__(self):
        return (self.product.name + " " + str(self.size))




class Stock(models.Model):
    product_detail = models.ForeignKey(ProductDetail, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    low_stock_threshold = models.PositiveIntegerField()
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.product_detail.product.name


class Supplier(models.Model):
    name = models.CharField(max_length=120)
    phone = models.IntegerField()
    comment = models.CharField(max_length=220, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return str(self.name)




class SuppliedProduct(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductDetail, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    unit_cost = models.DecimalField(max_digits=10, decimal_places=2)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.product.product.name


class Payment(models.Model):
    supplier = models.ForeignKey(Supplier, on_delete=models.DO_NOTHING)
    supplied_product = models.ForeignKey(SuppliedProduct, on_delete=models.DO_NOTHING)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    reference_number = models.CharField(max_length=220, blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.supplier.name



@receiver(pre_save, sender=ProductDetail,)
def setSKU(instance,**kwargs):


            if (instance.sku.strip() =="0"):

                sku = BarcodeEAN13.generateRandom([p.product for p in ProductDetail.objects.all()])
                count = 1
                while(ProductDetail.objects.filter(sku=sku).exists()):
                    sku = BarcodeEAN13.generateRandom()
                    print("found")
                    count =count+1
                    if (count==3):
                        break
                instance.sku = sku
                instance.save()


@receiver(post_save, sender=SuppliedProduct)
def productSupplied(sender, instance, created, **kwargs):
    if created:

           instance.total_cost = instance.unit_cost * instance.quantity
           instance.save()

           prouduct_detail = instance.product
           stock = Stock.objects.filter(product_detail =prouduct_detail)

           # stock doesn't exist product is new
           if(len(stock)==0):
               Stock.objects.create(product_detail=prouduct_detail,quantity=instance.quantity,low_stock_threshold=1)
               prouduct_detail.cost_price = instance.unit_cost
               prouduct_detail.save()
           else:

               stock = stock[0]
               prev_quantity = stock.quantity
               prev_cost_price = prouduct_detail.cost_price

               new_cost_price = ((prev_quantity*prev_cost_price)+(instance.quantity+instance.unit_cost))/(prev_quantity+instance.quantity)
               stock.quantity = stock.quantity + instance.quantity
               prouduct_detail.cost_price = new_cost_price
               prouduct_detail.save()
               stock.save()

store/forms.py
from django import forms
from .models import Product , ProductDetail ,Category

class ProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            field = self.fields[f]
            field.widget.attrs['class'] = 'form-control'

            if (f == "category"):
                field.widget.attrs['onchange'] = 'categoryChanged(this);'

    class Meta:
        model = Product
        exclude=['is_active', 'created_at' , 'updated_at']

class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Category
        exclude=['created_at' , 'updated_at']

class ProductDetailForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProductDetailForm, self).__init__(*args, **kwargs)
        for f in self.fields:
            self.fields[f].widget.attrs['class'] = 'form-control'

    class Meta:
        model = ProductDetail
        exclude=['created_at' , 'updated_at']

store/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import *

from django.http import JsonResponse
from pandas.core.indexes import category
from rest_framework.decorators import action
from rest_framework.response import Response

from .models import Product, ProductDetail, Stock ,SuppliedProduct
from .forms import ProductForm, CategoryForm

from django.contrib import admin
from .models import GroupedSizes


class GetProductBySkuView(View):
    """
    Fetch the product and its associated details by the given SKU.
    """
    def get(self, request, sku):
        print(sku)
        try:
            # Fetch the product detail record by the given SKU

            product_detail = ProductDetail.objects.get(sku=sku)

            # Fetch the product record
            product = product_detail.product

            # Fetch the stock information for the product detail
            #stock = Stock.objects.get(product_detail=product_detail)

            img = product.image.url if product.image != "" else ""
            # Prepare the response
            product_data = {
                "id": product_detail.id,
                "name": product.name,
                "color": product.color,
                "description": product.description,
                "category_id": product.category_id,
                "sku": product_detail.sku,
                "unit_price": product_detail.unit_price,
                #"cost_price": stock.cost_price,
                "image":  img,
                "is_active": product.is_active,
                "size": product_detail.size,
                #"quantity": stock.quantity,
                #"low_stock_threshold": stock.low_stock_threshold
            }

            return JsonResponse(product_data)

        except ProductDetail.DoesNotExist:
            # Handle the case where the product detail is not found
            return JsonResponse({"error": "Product Detail not found."}, status=404)
        except (Product.DoesNotExist):
            # Handle the case where the product or stock information is not found
            return JsonResponse({"error": "Product not found."}, status=404)

        except (Stock.DoesNotExist):
            # Handle the case where the product or stock information is not found
            return JsonResponse({"error": "stock information not found."}, status=404)
        except(Exception):
            return JsonResponse({"error": "Internal server error"}, status=404)


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = ProductDetail

class GenerateBarcode(View):
    def get(self,request,sku):
        product_detail =get_object_or_404(ProductDetail,sku=sku)
        stock = get_object_or_404(Stock,product_detail=product_detail)
        quantity = stock.quantity

        template = 'store/barcode.html'
        context = {'product_detail':product_detail,'range':range(quantity),'quantity':quantity}

        context = {
            **context,
            **admin.site.each_context(request),

        }
        return render(request, template, context)




class ProductListView(LoginRequiredMixin, View):

    def get(self,request):
        product_list = Product.objects.all()
        product_form = ProductForm()

        DetailFormSet = inlineformset_factory(Product, ProductDetail,  fields='__all__' , can_delete_extra=True , extra=6)
        formset = DetailFormSet()
        context = {'product_list':product_list,
                   'product_form':product_form,
                   'formset':formset ,
                   }

        return render(request, 'store/product_list.html', context=context)

def addProduct(request):

        product_form = ProductForm()
        category_form = CategoryForm()


        context = {
                   'product_form':product_form,
                   'category_form':category_form,

                   }

        return render(request, 'store/add_product.html', context=context)

templates/store/add_product.html
{% extends 'store/inventory_base.html' %}


    {% block content %}


  <!-- ========================= SECTION CONTENT ========================= -->

  <section class="container-fluid m-3 " id="content">
    <div class="row">

      <div class="col">
        <div class="container">
          <div class="row ">
            <div class="col-md-3 ">
              <div class="card">
                <div class="card-header py-1">
                  <label>Product</label>
                </div>
                <div class="card-body">

                  {% for field in product_form %}
                      {% if field.label == "Category" %}
                          <label>{{field.label}}</label>
                          <div class="input-group ">


                              {{field}}

                              <div class="input-group-append">
                                <button class="input-group-text" id="add-catagory">+</button>
                              </div>
                          </div>
                      {% else %}
                          <div class="form-group">
                          <label>{{field.label}}</label>
                          {{field}}
                  </div>
                      {% endif %}

                  {% endfor %}

                </div>
              </div>

            </div>
            <div class="col-md-9">
              <div class="card">
                <div class="card-header py-1">
                  <h5 class="text-center">Product Details</h5>
                </div>
                <div class="card-body">
                  <table class="table table-hover table-bordered my_table">
                    <thead>
                      <th>Size</th>
                      <th class="">
                        <div class="d-flex justify-content-between">
                          <span>Cost</span> <input type="checkbox" class="form-check-input bg-secondary" checked id="check_cost"
                            value="">
                        </div>
                      </th>
                      <th class="">
                        <div class="d-flex justify-content-between">
                          <span>Price</span> <input type="checkbox" id="check_price" checked
                            class="form-check-input bg-secondary" value="">
                        </div>
                      </th>
                      <th class="">
                        <div class="d-flex justify-content-between">
                          <span>SKU</span> <input type="checkbox" id="check_sku" checked class="form-check-input bg-secondary"
                            value="">
                        </div>
                      </th>
                      <th class="">
                        <div class="d-flex justify-content-between">
                          <span>Qty</span> <input type="checkbox" class="form-check-input bg-secondary" checked
                            id="check_qty" value="">
                        </div>
                      </th>


                      <th class="text-center"><button class="btn btn-outline-secondary btn-round py-0" id="add-button">+</button></th>
                    </thead>
                    <tbody>

                      <tr>

                        <td class="p-1"><input class="form-control" /></td>
                        <td class="p-1"><input class="form-control field-cost" type="number" /></td>
                        <td class="p-1"><input class="form-control field-price" type="number" /></td>
                        <td class="p-1"><input class="form-control field-sku" type="number" /></td>
                        <td class="p-1"><input class="form-control field-qty" type="number" /></td>
                        <td class="p-1 text-center"><button class="btn btn-danger btn-round remove-row"><i class="fa fas-trash">-</i></button></td>
                      </tr>

                      <tr>

                        <td class="p-1"><input class="form-control" /></td>
                        <td class="p-1"><input class="form-control field-cost" type="number" /></td>
                        <td class="p-1"><input class="form-control field-price" type="number" /></td>
                        <td class="p-1"><input class="form-control field-sku" type="number" /></td>
                        <td class="p-1"><input class="form-control field-qty" type="number" /></td>
                        <td class="p-1 text-center"><button class="btn btn-danger btn-round remove-row"><i class="fa fas-trash">-</i></button></td>
                      </tr>

                      <tr>

                        <td class="p-1"><input class="form-control" /></td>
                        <td class="p-1"><input class="form-control field-cost" type="number" /></td>
                        <td class="p-1"><input class="form-control field-price" type="number" /></td>
                        <td class="p-1"><input class="form-control field-sku" type="number" /></td>
                        <td class="p-1"><input class="form-control field-qty" type="number" /></td>
                        <td class="p-1 text-center"><button class="btn btn-danger btn-round remove-row"><i class="fa fas-trash">-</i></button></td>
                      </tr>




                    </tbody>
                  </table>


                  <div class="row px-3">
                    <button class="btn btn-outline-secondary btn-block" id="add-product">Add</button>

                  </div>

                </div>

              </div>

            </div>
            <div class="col mt-3">
              <div class="card">
                <div class="card-header">
                  <h5 class="text-center">Stock Details</h5>
                </div>
                <div class="card-body">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <td>#</td>
                        <td>Size</td>
                        <td>Supplied</td>
                        <td>Sold</td>
                        <td>Lost</td>
                        <td>Available</td>
                      </tr>

                    </thead>
                    <tbody>
                      <tr>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>1</td>
                      </tr>
                      <tr>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>1</td>
                      </tr>
                      <tr>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>1</td>
                      </tr>
                      <tr>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>2</td>
                        <td>1</td>
                        <td>1</td>
                      </tr>



                    </tbody>
                  </table>
                  <div>

                  </div>
                </div>
              </div>
            </div>
          </div><!-- container //  -->

        </div>

      </div>

  </section>
  <section class="section-content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-8 right">


        </div>

      </div>
    </div>
  </section>


  <!-- Section Modal -->
  <!-- The Modal -->
  <!-- Modal -->
  <div class="modal fade" id="myModal" aria-labelledby="myModalLabel" >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="myModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form  id="category_form">
        <div class="modal-body">


          {{category_form.as_p}}

        </div>
        <div class="modal-footer">
          <button type="reset" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Save</button>
        </div>
         </form>
      </div>
    </div>
  </div>

 {% endblock %}
  <!-- ========================= SECTION CONTENT END// ========================= -->


    {% block scripts %}
  <script>
    $(document).ready(function () {

      //sidebar
      //toggle side bar;
      $('#toggle-btn').click(function(){
        $('#sidebar').toggleClass('minimized');
        $('#content').toggleClass('expanded');
      });
      // animations

      $('.list-group-item').each(function (index) {
        $(this).css('animation-delay', (index * 0.1) + 's');
      });

      //modals
      $('#add-catagory').click(function () {
        $('#myModal').modal('show');
      });


      $('#add-product').click(function(){
        swal("perfect",'successfull', "success");
      });

      // table operations

      // add row
      $('#add-button').click(function () {
        addNewRow();
      });

      // remove row
      $('.my_table').on('click', '.remove-row', function () {
        $(this).closest('tr').remove();
      });
    });
  </script>

<script> //add row
  function addNewRow(size) {
    var newRow = $('<tr></tr>');
    newRow.html(`
        <td class="p-1"><input class="form-control field-size" ${size ? 'value="' + size + '"' : ''} /></td>
        <td class="p-1"><input class="form-control field-cost" type="number" /></td>
        <td class="p-1"><input class="form-control field-price" type="number" /></td>
        <td class="p-1"><input class="form-control field-sku" type="number" /></td>
        <td class="p-1"><input class="form-control field-qty" type="number" /></td>
        <td class="p-1 text-center"><button class="btn btn-danger btn-round remove-row">-</button></td>
    `);
    $('.my_table tbody').append(newRow);
    setDependecy();
}
</script>

  <script>
    $(function () {
      setDependecy();
    });

    function setDependecy() {

      handleCheckboxDependentFields('#check_cost', '.field-cost');
      handleCheckboxDependentFields('#check_price', '.field-price');
      handleCheckboxDependentFields('#check_sku', '.field-sku');
      handleCheckboxDependentFields('#check_qty', '.field-qty');
    }

    function handleCheckboxDependentFields(checkboxSelector, fieldSelector) {
      const $checkbox = $(checkboxSelector);
      const $inputs = $(fieldSelector);
      let currentValue = '';

      $inputs.on('keyup', function () {
        currentValue = $(this).val();
        if ($checkbox.is(':checked')) {
          $inputs.val(currentValue);
        }
      });

      $checkbox.on('change', function () {
        if (this.checked) {
          $inputs.val(currentValue);
        } else {
          $inputs.val('');
        }
      });

      // Set initial state of input fields based on checkbox state
      $inputs.each(function () {
        if ($checkbox.is(':checked')) {
          $(this).val(currentValue);
        } else {
          $(this).val('');
        }
      });
    }
  </script>


<script>

    function categoryChanged(input){

        var  category = $("#id_category");
        const categoryId = $("#id_category option:selected").val();
        if (categoryId == ''){
         $('.my_table tbody').empty();
        }
        else{
          $.ajax({
             url: '/api/grouped-sizes/filter_by_category/', // api url
             type: 'GET',
             data: {
                        category_id: categoryId   //url parameter
                    },
              success:function(data){
                            $('.my_table tbody').empty();
                            if (data.length > 0) {
                            data.forEach(function(groupedSize) {


                                addNewRow(groupedSize.size);
                            });
                        } else {
                            console.log('<p>No grouped sizes found for this category.</p>');
                             addNewRow();
                        }

           },

       failure:function(data){
              alert('got an error dude');
       }
    });

        }


    }

</script>

{% csrf_token %}
<script>
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
</script>

<script>
    $("#category_form").submit(function (e) {

    e.preventDefault();

    var serializedData = $(this).serialize();

    $.ajax({
       type:'POST',
       headers:{
            'X-CSRFToken': csrftoken
        },
       url: '/api/categories/' ,
       data: serializedData,
       success : function(response){
           $("#myModal").modal("toggle")
           $("#category_form").trigger('reset');
           var c = loadCategories();


           alert('dkdk');
           //swal("perfect",'successfull', "Category added successfully");

       },
       error: function(xhr, status, error) {
            // Handle the error
            swal("Error",'error', "Something went wrong.");


        }
     })
   });

</script>
<script>
  function loadCategories(){
   var categories ;
   $.ajax({
       type:'GET',

       url: '/api/categories/' ,
       success : function(data){
          categories = data;
          console.log(categories);

       },
       error: function(xhr, status, error) {
            // Handle the error
            swal("Error",'error', "Something went wrong.");


        }
     });
     return categories;
  }
</script>
    {% endblock %}
</body>

</html>

templates/store/barcode.html
{% extends 'admin/base_site.html' %}


{% load static %}
{% block header %}

<link href="{% static 'pos/assets/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block content %}
<style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 2px;
            margin: 2px;
        }

        th {
            background-color: #f2f2f2;
        }

</style>

<div id="content" class="container">
    <h1><b>Generate Barcode</b></h1>
    <div class="alert alert-info">
        <strong>Info !</strong> If quantity is 0 by default be sure product is out of stock.
    </div>
    <div class="m-auto col-md-5">
        <input type="number" id="quantity" value="{{ quantity }}" oninput="display_barcode(this)">
        <button class="btn btn-secondary btn-sm w-25 " onclick="printDocument('barcode_area')">
        <i class="fas fa-pdf"></i>Print
        </button>
    </div>


        <div class="m-auto col-md-5  my-3" id="barcode_area">



    </div>



</div>


<script src="{% static 'pos/assets/js/jquery-3.5.1.js' %}" type="text/javascript"></script>
<script src="{% static 'pos/assets/js/JsBarcode.all.min.js' %}" type="text/javascript"></script>

<script>
    function render_sku(id){
    JsBarcode(id, "{{product_detail.sku}}", {
                    format: "EAN13",
                    displayValue: true,
                    fontSize: 14,
                    width: 2,
                    height: 60
                    });
    }

</script>

<script>

       function display_barcode(){
       var barcode_area = $('#barcode_area');
       var quantity = $('#quantity').val();
       //remove previous
       $('#barcode_area .row').remove();
       for (let i = 0; i < quantity; i++) {
            //create the svg tag
            barcode_area.append(`<div class="card my-2 row" style="page-break-before:always;">
                                        <div class="text-bold text-center">
                                            <span >{{product_detail.product.name}}</span>
                                            <span >{{product_detail.size}}</span><br>
                                            <svg id="sku"></svg>
                                        </div>
                                   </div>`);
            //display the sku
            render_sku("#sku");

        }
       }

       function printDocument(divName) {
                var printContents = document.getElementById(divName).innerHTML;
                var originalContents = document.body.innerHTML;

                document.body.innerHTML = printContents;

                window.print();

                document.body.innerHTML = originalContents;



       }

display_barcode();

</script>
{% endblock %}

templates/store/product_list.html
{% extends 'includes/base.html' %}

{% block content %}
<div class="container">

<div class="card">
    <div class="row ">


        <div class="col-sm-4 ">
          {{product_form.as_p}}


        </div>


        <div class="col-sm-4 col-md-4 ">
          <div><input class="form-control"/></div>
          <div><input class="form-control"/></div>
          <div><input class="form-control"/></div>
          <div><input class="form-control"/></div>
          <div><input class="form-control"/></div>



        </div>


  </div>

</div>





  <h3>Products</h3>
<br>

  <table class="display table table-bordered" id='' style="width:100%;">

    <thead class="table-dark">
      <tr>
        <th>Product Name</th>
        <th>Category</th>
        <th>Available</th>
        <th>Created At</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for product in product_list %}
        <tr>
          <td>{{ product.name }}</td>
          <td>{{ product.category }}</td>
          <td>{{ product.is_active }}</td>
          <td>{{ product.created_at }}</td>
          <td>
            <a  class="btn btn-sm btn-warning"><i class="fas fa-bars"></i> </a>
            <a  class="btn btn-sm btn-primary"><i class="fas fa-edit"></i></a>
            <a  class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td >No Product available</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a  class="btn btn-primary">Add New Products</a>
</div>
{% endblock %}

{% block script %}
    {% include "includes/messages.html" %}
{% endblock %}